export const FEATURES = [
  { group: "Traffic and Market", path: "/market/get-started", kind: "get-started", title: "Get Started", description: "Connect the site, Search Console, and GA4, then run the first crawl." },
  { group: "Traffic and Market", path: "/market/google-services", kind: "google-services", title: "Google Services", description: "Unified hub for GSC, GA4, PageSpeed, and Places after connect." },
  { group: "Traffic and Market", path: "/market/traffic-analytics", kind: "traffic-analytics", title: "Traffic Analytics", description: "Sessions, users, and engagement over time from stored analytics." },
  { group: "Traffic and Market", path: "/market/overview", kind: "market-overview", title: "Market Overview", description: "Category demand and competitor share. A scheduled note is stored." },
  { group: "Traffic and Market", path: "/market/top-pages", kind: "top-pages", title: "Top Pages", description: "Landing pages joined from stored Search Console and GA4 rows." },
  { group: "Traffic and Market", path: "/market/ga4-landing-pages", kind: "ga4-landing-pages", title: "GA4 Landing Pages", description: "Top landing pages from Google Analytics 4." },
  { group: "Traffic and Market", path: "/market/competitor-monitoring", kind: "competitor-monitoring", title: "Competitor Monitoring", description: "Competitor traffic and keyword overlap, saved each week." },
  { group: "Traffic and Market", path: "/market/traffic-distribution", kind: "traffic-distribution", title: "Traffic Distribution", description: "Organic, direct, paid, referral, social, and email." },
  { group: "Traffic and Market", path: "/market/ai-traffic", kind: "ai-traffic", title: "AI Traffic", description: "Visits that arrived from an AI product." },
  { group: "Traffic and Market", path: "/market/referral", kind: "referral", title: "Referral", description: "Referring sites, source, and medium." },
  { group: "Traffic and Market", path: "/market/organic-search", kind: "organic-search", title: "Organic Search", description: "Clicks, impressions, CTR, and average position." },
  { group: "Traffic and Market", path: "/market/gsc-countries", kind: "gsc-countries", title: "GSC by Country", description: "Search Console performance by country." },
  { group: "Traffic and Market", path: "/market/gsc-devices", kind: "gsc-devices", title: "GSC by Device", description: "Search Console performance by device." },
  { group: "AI Search", path: "/ai-search", kind: "ai-search", title: "AI Search", description: "Stored AI-answer snapshots and a scheduled summary." },
  { group: "AI Search", path: "/ai-search/audit", kind: "ai-search-audit", title: "AI Search Audit", description: "Crawl findings. Fixes are scored before a person applies them." },
  { group: "AI Search", path: "/ai-search/report", kind: "ai-visibility-report", title: "AI Search Visibility Report", description: "A stored report. Later views read the save." },
  { group: "Writing", path: "/writing/assistant", kind: "seo-writing", title: "SEO Writing Assistant", description: "A draft from the page and a brief. A person publishes it." },
  { group: "Writing", path: "/writing/topics", kind: "topic-research", title: "Topic Research", description: "Keyword clusters already stored for this project." },
  { group: "Writing", path: "/writing/template", kind: "seo-content-template", title: "SEO Content Template", description: "A template from the topic and stored headings." },
  { group: "Links", path: "/links/building", kind: "link-building", title: "Link Building", description: "Prospects and an outreach draft. A person sends it." },
  { group: "Links", path: "/links/backlinks", kind: "backlinks", title: "Backlinks", description: "Backlink table from the stored index." },
  { group: "Links", path: "/links/referring-domains", kind: "referring-domains", title: "Referring Domains", description: "Domains that link to the site." },
  { group: "Links", path: "/links/audit", kind: "backlink-audit", title: "Backlink Audit", description: "Flagged rows. A person reviews the queue." },
  { group: "Site", path: "/site/on-page", kind: "on-page-seo", title: "On Page SEO Checker", description: "Crawler findings for a URL, then a draft edit." },
  { group: "Site", path: "/site/audit", kind: "site-audit", title: "Site Audit", description: "Site-wide crawl plus speed. Monitor reuses this job." },
  { group: "Site", path: "/site/positions", kind: "position-tracking", title: "Position Tracking", description: "Rank history from stored checks." },
  { group: "Site", path: "/operator", kind: "seo-operator", title: "SEO Operator", description: "GSC opportunity → AI change → approve → execute on WordPress/Shopify/Webflow/custom → monitor." },
  { group: "Site", path: "/operator", kind: "cms-connectors", title: "CMS Connectors", description: "Connect WordPress, Shopify, Webflow, or a custom webhook for live execution." },
  { group: "Site", path: "/operator", kind: "change-history", title: "Change History", description: "Recorded site actions Searchify applied after approval." },
  { group: "Site", path: "/operator", kind: "outcome-monitor", title: "Outcome Monitor", description: "Track GSC outcomes after a CMS change is applied." },
  { group: "AI Visibility", path: "/visibility/analysis", kind: "ai-analysis", title: "AI Analysis", description: "A stored summary of prompt runs and AI answers." },
  { group: "AI Visibility", path: "/visibility/overview", kind: "visibility-overview", title: "Visibility Overview", description: "Search Console plus stored AI answers." },
  { group: "AI Visibility", path: "/visibility/competitors", kind: "competitor-research", title: "Competitor Research", description: "What competitors rank for." },
  { group: "AI Visibility", path: "/visibility/prompts", kind: "prompt-research", title: "Prompt Research", description: "Suggested prompts. The answers are stored." },
  { group: "Monitor", path: "/monitor/prompts", kind: "prompt-tracking", title: "Prompt Tracking", description: "The same prompts run on a schedule. The trend is stored." },
  { group: "Monitor", path: "/monitor/content", kind: "content-creation", title: "Content Creation", description: "A piece from an approved brief, then a score." },
  { group: "Content", path: "/content", kind: "content-dashboard", title: "Content Dashboard", description: "Pieces, status, and approvals." },
  { group: "Content", path: "/content/article", kind: "ai-article", title: "AI Article Generator", description: "An article from the brief and stored research." },
  { group: "Content", path: "/content/optimizer", kind: "content-optimizer", title: "Content Optimizer", description: "An edit draft. A person publishes it." },
  { group: "Content", path: "/content/repurpose", kind: "content-repurposing", title: "Content Repurposing", description: "A rewrite of a piece already in My Content." },
  { group: "Content", path: "/content/topics", kind: "topic-finder", title: "Topic Finder", description: "Stored keywords ranked for new topics." },
  { group: "Content", path: "/content/brief", kind: "seo-brief", title: "SEO Brief Generator", description: "A brief from stored headings and keyword rows." },
  { group: "Content", path: "/content/library", kind: "my-content", title: "My Content", description: "The library. Publish waits until a person agrees." },
];
