export const QUESTIONS = [
  { section: "YOUR SITE", type: "text", key: "site", question: "Which website should we set up first?", note: "Start with one website. You can add more after the first connection is working.", placeholder: "https://yourwebsite.com", required: true, inputType: "url" },
  { section: "YOUR SITE", type: "choice", key: "platform", question: "What platform is this website built on?", note: "This helps Searchify show the right connection steps.", options: [["WordPress", "WP", "Connect through a site-specific integration"], ["Shopify", "S", "Choose your store platform"], ["Webflow", "W", "Choose your website platform"], ["Something else", "+", "Tell us if you use another platform"]] },
  { section: "CONNECT YOUR SITE", type: "connect", key: "wordpress", question: "Ready to connect your WordPress site?", note: "Connect this site now. If you skip it, you can finish from Connections in the dashboard.", icon: "W", title: "WordPress connection", body: "A secure connection is limited to the selected site. Searchify asks for the site address, username, and application password.", action: "Connect WordPress" },
  { section: "CONNECT SEARCH DATA", type: "connect", key: "gsc", question: "Would you like to connect Search Console?", note: "Connect Google now, or leave it for the Connections screen. Searchify does not publish anything from this step.", icon: "G", title: "Google Search Console", body: "Read-only Search Console data for the property you select. Analytics can be chosen in the same Google step.", action: "Connect Search Console", providerNote: "You can disconnect or change the property later from Connections." },
  { section: "YOUR BUSINESS", type: "choice", key: "businessType", question: "Which best describes what your business sells?", note: "Choose the closest fit. Searchify uses this to keep recommendations relevant to your business model.", options: [["Services", "◈", "Appointments, projects or ongoing work"], ["Products", "▧", "Physical or digital products"], ["Information", "≋", "Publishing, education or resources"], ["Something else", "+", "A different business model"]] },
  { section: "YOUR MARKET", type: "choice", key: "reach", question: "Where do you serve or sell to customers?", note: "Choose the area you want Searchify to focus on first.", options: [["A local area", "⌖", "One town, city or service radius"], ["Several regions", "⌑", "Multiple cities or areas"], ["Nationally", "◎", "Across one country"], ["Worldwide", "◌", "Customers in multiple countries"]] },
  { section: "YOUR MARKET", type: "text", key: "market", question: "Which city, region or country should we start with?", note: "For local businesses, name your service area. For online businesses, name the market you want to grow.", placeholder: "e.g. Calgary, Alberta", required: true },
  { section: "YOUR GOALS", type: "text", key: "shortGoal", question: "What would meaningful progress look like in 90 days?", note: "Give a target if you know it. If not, Searchify can help establish a baseline after data is connected.", placeholder: "e.g. establish a baseline for qualified organic leads", optional: true },
  { section: "INDUSTRY CONTEXT", type: "choice", key: "industry", question: "Does your business cover a regulated or sensitive area?", note: "This tells Searchify when to slow down, show sources, and ask for review.", options: [["No special category", "✓", "None of these apply"], ["Health or supplements", "+", "Medical, wellness or supplement topics"], ["Finance or insurance", "$", "Financial services or credit topics"], ["Alcohol, gambling or adult", "!", "Restricted product or content categories"], ["Politics or public issues", "◉", "Political or public policy topics"], ["Another regulated area", "…", "I’ll describe it in the next step"]] },
  { section: "YOUR GUARDRAILS", type: "text", key: "avoid", question: "What claims, phrases or topics should Searchify avoid?", note: "Name any terms, promises or claims your team does not want used. You can skip this if there are none.", placeholder: "e.g. guaranteed results, unverified medical claims", optional: true, last: true },
];
